### ISSUE TITLE
Pip install: Syntax error when downloading pyxnat-0.9.5.2.tar.gz

### ISSUE THREAD

**Issue by Phildrummer** [pyxnat/pyxnat#178]
I can't seem to install pyxnat on my system. I get the following error:

```
Downloading pyxnat-0.9.5.2.tar.gz (537 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 538.0/538.0 kB 3.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-w44of4c0/pyxnat_5a692380f8a34e32b92653fa062b1d6c/setup.py", line 6, in <module>
          import pyxnat
        File "/tmp/pip-install-w44of4c0/pyxnat_5a692380f8a34e32b92653fa062b1d6c/pyxnat/__init__.py", line 13, in <module>
          from .core import Interface
        File "/tmp/pip-install-w44of4c0/pyxnat_5a692380f8a34e32b92653fa062b1d6c/pyxnat/core/__init__.py", line 4, in <module>
          from .interfaces import Interface
        File "/tmp/pip-install-w44of4c0/pyxnat_5a692380f8a34e32b92653fa062b1d6c/pyxnat/core/interfaces.py", line 19, in <module>
          from .select import Select
        File "/tmp/pip-install-w44of4c0/pyxnat_5a692380f8a34e32b92653fa062b1d6c/pyxnat/core/select.py", line 4, in <module>
          from .search import Search
        File "/tmp/pip-install-w44of4c0/pyxnat_5a692380f8a34e32b92653fa062b1d6c/pyxnat/core/search.py", line 15, in <module>
          from .errors import is_xnat_error, catch_error
        File "/tmp/pip-install-w44of4c0/pyxnat_5a692380f8a34e32b92653fa062b1d6c/pyxnat/core/errors.py", line 31
          except Exception, e:
                          ^
      SyntaxError: invalid syntax
      [end of output]

```

I am trying to install the latest version(1.6)

**Comment by jhuguetn** [comment]
Hi @Phildrummer, which command are you using for installing pyxnat? 
What context are you working with, which Python version are you using? 

Normally I would do as follows to install an specific package release,
```bash
pip install pyxnat==1.6
```
or, if you have pyxnat already installed, simply upgrade it,
```bash
pip install --upgrade pyxnat
```

**Comment by Phildrummer** [comment]
I am trying to install rtmidi and it uses some stuff as dependencies. I am installing it on a Raspberry Pi 1 Model B, which I think causes a lot of the issues. I think we can close this ticket for now.

**Comment by jhuguetn** [comment]
Ok, closing the issue.
