### ISSUE TITLE
tests failing on a Debian wheezy/sid box

### ISSUE THREAD

**Issue by yarikoptic** [pyxnat/pyxnat#33]
On current master release/0.9.1-51-g0e62fc5 (with my pull request release/0.9.1-52-g9e0d3d5) running via

```
$> PYTHONPATH=$PWD /usr/bin/nosetests -v --exclude="test_(del_provenance|attr_mset|subject._delete)" pyxnat
```

some tests fail (I have lxml 2.3.2 if that is of any relevance)

```
pyxnat.tests.xpass_test.test_find_plus_line ... ok
pyxnat.tests.xpass_test.test_find_token ... ok
pyxnat.tests.xpass_test.test_parse_xnat_pass ... ok
pyxnat.tests.xpath_test.test_xpath_checkout ... ERROR
pyxnat.tests.xpath_test.test_elements ... ERROR
pyxnat.tests.xpath_test.test_keys ... ERROR
pyxnat.tests.xpath_test.test_values ... ERROR
pyxnat.tests.xpath_test.test_element_attrs ... ERROR

======================================================================
ERROR: pyxnat.tests.xpath_test.test_xpath_checkout
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/tests/xpath_test.py", line 7, in test_xpath_checkout
    assert 'OAS1_0001' in central.xpath.subjects() and \
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/core/xpath_store.py", line 114, in subjects
    return self.__call__('//xnat:Subject/attribute::ID')
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/core/xpath_store.py", line 39, in __call__
    return self._tree.xpath(xpath, namespaces=self._nsmap)
  File "lxml.etree.pyx", line 1447, in lxml.etree._Element.xpath (src/lxml/lxml.etree.c:41728)
  File "xpath.pxi", line 321, in lxml.etree.XPathElementEvaluator.__call__ (src/lxml/lxml.etree.c:117734)
  File "xpath.pxi", line 239, in lxml.etree._XPathEvaluatorBase._handle_result (src/lxml/lxml.etree.c:116911)
  File "xpath.pxi", line 224, in lxml.etree._XPathEvaluatorBase._raise_eval_error (src/lxml/lxml.etree.c:116728)
XPathEvalError: Undefined namespace prefix

======================================================================
ERROR: pyxnat.tests.xpath_test.test_elements
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/tests/xpath_test.py", line 11, in test_elements
    assert 'fs:region' in central.xpath.elements()
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/core/xpath_store.py", line 139, in elements
    for element in self.__call__('//xnat:Subject/descendant::*'):
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/core/xpath_store.py", line 39, in __call__
    return self._tree.xpath(xpath, namespaces=self._nsmap)
  File "lxml.etree.pyx", line 1447, in lxml.etree._Element.xpath (src/lxml/lxml.etree.c:41728)
  File "xpath.pxi", line 321, in lxml.etree.XPathElementEvaluator.__call__ (src/lxml/lxml.etree.c:117734)
  File "xpath.pxi", line 239, in lxml.etree._XPathEvaluatorBase._handle_result (src/lxml/lxml.etree.c:116911)
  File "xpath.pxi", line 224, in lxml.etree._XPathEvaluatorBase._raise_eval_error (src/lxml/lxml.etree.c:116728)
XPathEvalError: Undefined namespace prefix

======================================================================
ERROR: pyxnat.tests.xpath_test.test_keys
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/tests/xpath_test.py", line 14, in test_keys
    assert 'ID' in central.xpath.keys()
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/core/xpath_store.py", line 119, in keys
    return self.element_keys('xnat:Subject')
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/core/xpath_store.py", line 163, in element_keys
    for element in self.__call__('//%s' % name):
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/core/xpath_store.py", line 39, in __call__
    return self._tree.xpath(xpath, namespaces=self._nsmap)
  File "lxml.etree.pyx", line 1447, in lxml.etree._Element.xpath (src/lxml/lxml.etree.c:41728)
  File "xpath.pxi", line 321, in lxml.etree.XPathElementEvaluator.__call__ (src/lxml/lxml.etree.c:117734)
  File "xpath.pxi", line 239, in lxml.etree._XPathEvaluatorBase._handle_result (src/lxml/lxml.etree.c:116911)
  File "xpath.pxi", line 224, in lxml.etree._XPathEvaluatorBase._raise_eval_error (src/lxml/lxml.etree.c:116728)
XPathEvalError: Undefined namespace prefix

======================================================================
ERROR: pyxnat.tests.xpath_test.test_values
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/tests/xpath_test.py", line 17, in test_values
    assert 'OAS1_0002' in central.xpath.values('ID')
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/core/xpath_store.py", line 124, in values
    return self.element_values('xnat:Subject', key)
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/core/xpath_store.py", line 174, in element_values
    for subject in self.__call__('//%s' % name):
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/core/xpath_store.py", line 39, in __call__
    return self._tree.xpath(xpath, namespaces=self._nsmap)
  File "lxml.etree.pyx", line 1447, in lxml.etree._Element.xpath (src/lxml/lxml.etree.c:41728)
  File "xpath.pxi", line 321, in lxml.etree.XPathElementEvaluator.__call__ (src/lxml/lxml.etree.c:117734)
  File "xpath.pxi", line 239, in lxml.etree._XPathEvaluatorBase._handle_result (src/lxml/lxml.etree.c:116911)
  File "xpath.pxi", line 224, in lxml.etree._XPathEvaluatorBase._raise_eval_error (src/lxml/lxml.etree.c:116728)
XPathEvalError: Undefined namespace prefix

======================================================================
ERROR: pyxnat.tests.xpath_test.test_element_attrs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/tests/xpath_test.py", line 20, in test_element_attrs
    assert isinstance(central.xpath.element_attrs('fs:region'), list)
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/core/xpath_store.py", line 153, in element_attrs
    for element in self.__call__('//%s' % name):
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/core/xpath_store.py", line 39, in __call__
    return self._tree.xpath(xpath, namespaces=self._nsmap)
  File "lxml.etree.pyx", line 1447, in lxml.etree._Element.xpath (src/lxml/lxml.etree.c:41728)
  File "xpath.pxi", line 321, in lxml.etree.XPathElementEvaluator.__call__ (src/lxml/lxml.etree.c:117734)
  File "xpath.pxi", line 239, in lxml.etree._XPathEvaluatorBase._handle_result (src/lxml/lxml.etree.c:116911)
  File "xpath.pxi", line 224, in lxml.etree._XPathEvaluatorBase._raise_eval_error (src/lxml/lxml.etree.c:116728)
XPathEvalError: Undefined namespace prefix

======================================================================
FAIL: pyxnat.tests.resources_test.test_get_file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/tests/resources_test.py", line 159, in test_get_file
    assert os.path.exists(custom)
AssertionError: 
    assert <module 'os' from '/usr/lib/python2.7/os.pyc'>.path.exists('/home/yoh/.tmp/6914adbe815611e29d4700216a237482')
    assert not <module 'os' from '/usr/lib/python2.7/os.pyc'>.path.exists('/home/yoh/.tmp/nosetests@central.xnat.org/970603a3479cbb338c0c173e92ccdb6c')
    <File Object> hello.txt.get()
>>  assert <module 'os' from '/usr/lib/python2.7/os.pyc'>.path.exists('/home/yoh/.tmp/6914adbe815611e29d4700216a237482')
    <module 'os' from '/usr/lib/python2.7/os.pyc'>.remove('/home/yoh/.tmp/6914adbe815611e29d4700216a237482')


======================================================================
FAIL: pyxnat.tests.resources_test.test_get_dir_file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/deb/gits/pkg-exppsy/pyxnat/pyxnat/tests/resources_test.py", line 184, in test_get_dir_file
    assert os.path.exists(custom)
AssertionError: 
    assert <module 'os' from '/usr/lib/python2.7/os.pyc'>.path.exists('/home/yoh/.tmp/69e1c33a815611e29d4700216a237482')
    assert not <module 'os' from '/usr/lib/python2.7/os.pyc'>.path.exists('/home/yoh/.tmp/nosetests@central.xnat.org/28c4701fbe69c6677c6c4fff0f3cbff6')
    <File Object> dir/hello.txt.get()
>>  assert <module 'os' from '/usr/lib/python2.7/os.pyc'>.path.exists('/home/yoh/.tmp/69e1c33a815611e29d4700216a237482')
    <module 'os' from '/usr/lib/python2.7/os.pyc'>.remove('/home/yoh/.tmp/69e1c33a815611e29d4700216a237482')


Name                        Stmts   Miss  Cover   Missing
---------------------------------------------------------
pyxnat                         19      0   100%   
pyxnat.core                     8      0   100%   
pyxnat.core.array              51     24    53%   25, 30, 33, 36, 41, 44, 167-190
pyxnat.core.attributes         56     10    82%   43-47, 100-109, 146, 185
pyxnat.core.cache             201     69    66%   29, 31, 38-47, 78-79, 113, 127-128, 138-145, 148-149, 159, 191, 198-204, 207, 210, 220-223, 250, 255-264, 279-292, 298, 304-312, 322, 330, 336-345, 356, 383-384, 386-387
pyxnat.core.downloadutils      51     44    14%   32-37, 87-150
pyxnat.core.errors             63     29    54%   12-24, 27-43, 54-60, 64, 66, 72-75
pyxnat.core.help              279    163    42%   7-8, 62-65, 195, 287, 293-313, 340, 386-403, 406-424, 428-449, 452-478, 487-512, 515-516, 519-520, 523-524, 527-528, 531-552, 555-578, 581-602, 606-608, 664-681, 684-708
pyxnat.core.httputil           14      0   100%   
pyxnat.core.interfaces        235     82    65%   102-103, 119, 125-134, 143, 147, 152, 155, 199, 204, 213-217, 228-231, 247, 254, 262-264, 299, 312, 326-343, 349-355, 369-371, 413, 426, 436-438, 445, 467-482, 497-519, 522, 525, 531-532
pyxnat.core.jsonutil          152     26    83%   15, 30, 41, 60-77, 81, 86, 119-126, 142, 159, 240, 291-292, 300-301, 319
pyxnat.core.manage            102     56    45%   56, 66-89, 104-116, 120-121, 136-147, 153-154, 201, 211, 223, 236, 250, 269-279, 294-297, 306-308, 317
pyxnat.core.pathutil           17     15    12%   4-23
pyxnat.core.provenance        126     30    76%   47-48, 51, 54, 72-74, 91, 94, 106-109, 130-138, 141-149, 240, 291-304
pyxnat.core.resources         850    366    57%   54-57, 144, 150, 153, 178-183, 186, 200, 209, 220, 289-312, 319-323, 363, 367, 372-384, 405, 418, 443-448, 455-460, 465-468, 541-551, 554, 604, 623, 650-653, 667-680, 683-684, 696-713, 716-739, 745-746, 761, 764-797, 830-849, 856-861, 866-869, 901, 903-906, 908-909, 913, 956, 962, 967-968, 1009, 1024, 1035-1037, 1149, 1152-1154, 1160-1171, 1206-1290, 1299-1322, 1338, 1349, 1359, 1372, 1383, 1393, 1398, 1404, 1409, 1423-1434, 1452, 1463, 1473, 1477, 1483, 1487, 1490, 1516, 1556-1612, 1621-1633, 1641-1644, 1651, 1658, 1666-1668, 1674-1676, 1716, 1749, 1784, 1788, 1829-1833, 1860, 1863-1865, 1911-1917, 1927, 1932, 1937, 1947, 1967, 1974-1975, 1978-1979, 1985, 1992-1993, 1996-1997, 2003, 2010-2011, 2014-2015, 2022, 2033, 2045, 2070-2078, 2098, 2118
pyxnat.core.schema             49     36    27%   69-122, 125-127, 133-140, 147
pyxnat.core.search            260    111    57%   140, 186-220, 223-242, 245-286, 317-322, 375, 409-410, 413-421, 448-449, 496-499, 519, 552-569, 588-609, 617, 681, 683-687, 689-690, 694, 703, 718-719, 722, 728
pyxnat.core.select            169     27    84%   76, 116, 132, 178, 184-185, 266-268, 280-282, 287-289, 292-294, 297, 319-322, 325, 337, 351, 361-366, 370
pyxnat.core.tags               91     65    29%   18-19, 23-31, 34, 37, 40, 43-44, 50-53, 57, 60-64, 67-74, 77-78, 81, 84-88, 91-97, 100-107, 110-116, 119-124
pyxnat.core.uriutil            77     17    78%   60-67, 108-112, 122-134
pyxnat.core.users              23      2    91%   80-82
pyxnat.core.xpass              44      5    89%   6, 10-15
pyxnat.core.xpath_store        92     42    54%   12-19, 37, 46-52, 59-62, 71-86, 101-102, 129, 140-146, 154-156, 164-167, 175-177, 182
---------------------------------------------------------
TOTAL                        3029   1219    60%   
----------------------------------------------------------------------
Ran 91 tests in 836.030s

FAILED (errors=5, failures=2)
```

**Comment by xgrg** [comment]
Please open a new issue if the problem still holds.
